### ISSUE TITLE
Hook up beer detail view to beer model object. 

### ISSUE THREAD

**Issue by benlachman** [AthensWorks/OBWapp-iOS#2]
Currently it's only partially done.

**Comment by benlachman** [comment]
@zperrault think you're up to this one?

**Comment by sloanelybutsurely** [comment]
@benlachman I sure can try.

**Comment by benlachman** [comment]
Awesome. We cleaned up a bunch of the broken bits last night so this should be eminently doable now. Mostly it's just hooking up existing labels to the data model properties in `BeerDetailViewController`. We're getting close on time though, so sooner the better!

**Comment by benlachman** [comment]
Also, feel free to do this via a branch and PR, vs directly committing to develop :-)
