### ISSUE TITLE
Add app icon.

### ISSUE THREAD

**Issue by benlachman** [AthensWorks/OBWapp-iOS#4]
This needs to be an asset at multiple resolutions. Here's an [oft-used PSD app icon template](http://appicontemplate.com/ios8). I think you have access to a bunch of OBW assets, yes?

If you want, you can stick them in the root directory and commit them, then I'll move into place.

**Comment by benlachman** [comment]
@Tropical-Wilson What think ye?

**Comment by djDAOjones** [comment]
ah, sorry I missed this earlier, yes, I will have a go

I do not have the OBW media assets though, were they located?

**Comment by benlachman** [comment]
Any luck? I'm hoping to submit this in the next day or so.

**Comment by djDAOjones** [comment]
Hey, sorry for lack of action!

Apologies for the inconvenience, but I recently blanked my machine, and it’s easier for me just to email (OBW logo in iOS icon form attached). Will get Git reinstalled at my next hack night.

This is just the OBW general logo - are we running with that? It’s quite the design and I’m not sure how well it could be modified, however, if we need to change it so be it (image of general logo also attached).
